In [1]:
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("Bank_Marketing.csv")

# Preview
df.head()

  age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0  58;"management";"married";"tertiary";"no";2143...
1  44;"technician";"single";"secondary";"no";29;"...
2  33;"entrepreneur";"married";"secondary";"no";2...
3  47;"blue-collar";"married";"unknown";"no";1506...
4  33;"unknown";"single";"unknown";"no";1;"no";"n...

In [4]:
df.head()

  age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0  58;"management";"married";"tertiary";"no";2143...
1  44;"technician";"single";"secondary";"no";29;"...
2  33;"entrepreneur";"married";"secondary";"no";2...
3  47;"blue-collar";"married";"unknown";"no";1506...
4  33;"unknown";"single";"unknown";"no";1;"no";"n...

In [5]:
print([col.lower() for col in df.columns])

['age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"']

In [6]:
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

In [8]:
if 'y' in df.columns:
    X = df.drop('y', axis=1)
    y = df['y']
else:
    print("Column 'y' not found. Available columns:", df.columns)

Column 'y' not found. Available columns: Index(['age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"'], dtype='str')

In [10]:
print(df.columns)

Index(['age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"'], dtype='str')

In [14]:
df.head()

  age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0  58;"management";"married";"tertiary";"no";2143...
1  44;"technician";"single";"secondary";"no";29;"...
2  33;"entrepreneur";"married";"secondary";"no";2...
3  47;"blue-collar";"married";"unknown";"no";1506...
4  33;"unknown";"single";"unknown";"no";1;"no";"n...

In [19]:
print(df.columns)
df.head()

Index(['age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"'], dtype='str')

  age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0  58;"management";"married";"tertiary";"no";2143...
1  44;"technician";"single";"secondary";"no";29;"...
2  33;"entrepreneur";"married";"secondary";"no";2...
3  47;"blue-collar";"married";"unknown";"no";1506...
4  33;"unknown";"single";"unknown";"no";1;"no";"n...

In [22]:
print('y_test' in globals())

False

In [27]:
print(df.head())

  age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0  58;"management";"married";"tertiary";"no";2143...
1  44;"technician";"single";"secondary";"no";29;"...
2  33;"entrepreneur";"married";"secondary";"no";2...
3  47;"blue-collar";"married";"unknown";"no";1506...
4  33;"unknown";"single";"unknown";"no";1;"no";"n...