In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load dataset
df = pd.read_csv("crime_india.csv")

# Preview data
df.head()

  S. No. (Col.1)  ... Rank Based on Crime Rate (2016) (Col.11)
0              1  ...                                     15.0
1              2  ...                                     17.0
2              3  ...                                      5.0
3              4  ...                                     22.0
4              5  ...                                     14.0

[5 rows x 11 columns]

In [3]:
# Dataset info
df.info()

# Check missing values
df.isnull().sum()

# Describe dataset
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 11 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   S. No. (Col.1)                                            38 non-null     str
 1   Category (Col.2)                                          38 non-null     str
 2   State/UT (Col.3)                                          38 non-null     str
 3   Year - 2014 (Col.4)                                       38 non-null     int64
 4   Year - 2015 (Col.5)                                       38 non-null     int64
 5   Year - 2016 (Col.6)                                       38 non-null     int64
 6   Percentage Share of State/UT (2016) (Col.7)               38 non-null     float64
 7   Rank Based on Incidence/ Percentage share (2016) (Col.8)  36 non-null     float64
 8   Mid-Year Projected Population (In Lakhs) (2016)+ (Col.9)  38 non-null     float64
 9   Rate of Cognizable Crimes (IPC) (2016)++ (Col.10)         38 non-null     float64
 10  Rank Based on Crime Rate (2016) (Col.11)                  36 non-null     float64
dtypes: float64(5), int64(3), str(3)
memory usage: 4.0 KB

       Year - 2014 (Col.4)  ...  Rank Based on Crime Rate (2016) (Col.11)
count         3.800000e+01  ...                                 36.000000
mean          1.500823e+05  ...                                 18.500000
std           4.316331e+05  ...                                 10.535654
min           8.100000e+01  ...                                  1.000000
25%           3.598250e+03  ...                                  9.750000
50%           5.176750e+04  ...                                 18.500000
75%           1.617605e+05  ...                                 27.250000
max           2.687767e+06  ...                                 36.000000

[8 rows x 8 columns]

In [5]:
df = df.bfill()

In [6]:
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

In [7]:
# Assume last column is target (change if needed)
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [10]:
for col in X_train.columns:
    if X_train[col].dtype == 'object':
        print(col, X_train[col].unique()[:5])

In [11]:
print(X_train.head())

   S. No. (Col.1)  ... Rate of Cognizable Crimes (IPC) (2016)++ (Col.10)
24             25  ...                                             295.7
15             16  ...                                             121.9
17             18  ...                                             227.3
8               9  ...                                             188.1
16             17  ...                                             120.9

[5 rows x 10 columns]

In [13]:
print(X_train.dtypes)
print(X_train.head())

S. No. (Col.1)                                                  str
Category (Col.2)                                                str
State/UT (Col.3)                                                str
Year - 2014 (Col.4)                                           int64
Year - 2015 (Col.5)                                           int64
Year - 2016 (Col.6)                                           int64
Percentage Share of State/UT (2016) (Col.7)                 float64
Rank Based on Incidence/ Percentage share (2016) (Col.8)    float64
Mid-Year Projected Population (In Lakhs) (2016)+ (Col.9)    float64
Rate of Cognizable Crimes (IPC) (2016)++ (Col.10)           float64
dtype: object
   S. No. (Col.1)  ... Rate of Cognizable Crimes (IPC) (2016)++ (Col.10)
24             25  ...                                             295.7
15             16  ...                                             121.9
17             18  ...                                             227.3
8               9  ...                                             188.1
16             17  ...                                             120.9

[5 rows x 10 columns]

In [17]:
'y_pred_dt' in globals()

False

In [19]:
hasattr(rf_model, "estimators_")

False

In [22]:
print(X_train.columns)

Index(['S. No. (Col.1)', 'Category (Col.2)', 'State/UT (Col.3)',
       'Year - 2014 (Col.4)', 'Year - 2015 (Col.5)', 'Year - 2016 (Col.6)',
       'Percentage Share of State/UT (2016) (Col.7)',
       'Rank Based on Incidence/ Percentage share (2016) (Col.8)',
       'Mid-Year Projected Population (In Lakhs) (2016)+ (Col.9)',
       'Rate of Cognizable Crimes (IPC) (2016)++ (Col.10)'],
      dtype='str')