In [1]:
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("Formula1_2025Season_RaceResults.csv")

df.head()

       Track Position  No  ... Points Set Fastest Lap  Fastest Lap Time
0  Australia        1   4  ...     25             Yes          1:22.167
1  Australia        2   1  ...     18              No          1:23.081
2  Australia        3  63  ...     15              No          1:25.065
3  Australia        4  12  ...     12              No          1:24.901
4  Australia        5  23  ...     10              No          1:24.597

[5 rows x 11 columns]

In [4]:
print(df.columns)
df.columns = df.columns.str.strip()
print(df.columns)

Index(['Track', 'Position', 'No', 'Driver', 'Team', 'Starting Grid', 'Laps',
       'Time/Retired', 'Points', 'Set Fastest Lap', 'Fastest Lap Time'],
      dtype='str')
Index(['Track', 'Position', 'No', 'Driver', 'Team', 'Starting Grid', 'Laps',
       'Time/Retired', 'Points', 'Set Fastest Lap', 'Fastest Lap Time'],
      dtype='str')

In [7]:
print(df.columns)

Index(['Track', 'Position', 'No', 'Driver', 'Team', 'Starting Grid', 'Laps',
       'Time/Retired', 'Points', 'Set Fastest Lap', 'Fastest Lap Time'],
      dtype='str')

In [8]:
df.columns = df.columns.str.strip().str.replace(" ", "")

In [12]:
expected = ['Driver', 'Team', 'GridPosition', 'FastestLap', 'DNF', 'Weather']
missing = [col for col in expected if col not in df.columns]
print(missing)

['GridPosition', 'FastestLap', 'DNF', 'Weather']

In [16]:
df.head()

       Track Position  No  ...  Points  SetFastestLap  FastestLapTime
0  Australia        1   4  ...      25            Yes        1:22.167
1  Australia        2   1  ...      18             No        1:23.081
2  Australia        3  63  ...      15             No        1:25.065
3  Australia        4  12  ...      12             No        1:24.901
4  Australia        5  23  ...      10             No        1:24.597

[5 rows x 11 columns]

In [24]:
df.head()

       Track Position  No  ...  Points  SetFastestLap  FastestLapTime
0  Australia        1   4  ...      25            Yes        1:22.167
1  Australia        2   1  ...      18             No        1:23.081
2  Australia        3  63  ...      15             No        1:25.065
3  Australia        4  12  ...      12             No        1:24.901
4  Australia        5  23  ...      10             No        1:24.597

[5 rows x 11 columns]

In [27]:
print("y_test" in globals())

False