In [1]:
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# ML Models
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier

# Metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load your dataset
df = pd.read_csv("kap.csv")

# Preview
df.head()

                publishedAt  dislikeCount  ...  viewCount likeCount
0  2016-04-21T21:59:27.000Z         118.0  ...   973798.0    4626.0
1  2015-09-08T15:58:52.000Z        1522.0  ...  5391383.0   36486.0
2  2015-09-08T15:18:07.000Z         574.0  ...  2298981.0   19948.0
3  2015-09-01T19:45:01.000Z         160.0  ...  1070520.0    5861.0
4  2015-08-17T20:09:15.000Z         888.0  ...  8185818.0   79948.0

[5 rows x 8 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

# Check missing values
print(df.isnull().sum())

(199, 8)
<class 'pandas.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publishedAt   199 non-null    str
 1   dislikeCount  187 non-null    float64
 2   url           187 non-null    str
 3   id            199 non-null    str
 4   commentCount  187 non-null    float64
 5   title         199 non-null    str
 6   viewCount     187 non-null    float64
 7   likeCount     187 non-null    float64
dtypes: float64(4), str(4)
memory usage: 34.4 KB
None
       dislikeCount  commentCount     viewCount      likeCount
count    187.000000    187.000000  1.870000e+02     187.000000
mean    1052.192513   3408.374332  8.347763e+06   51971.989305
std     1379.607251   3973.737811  9.981489e+06   62823.429764
min       23.000000     43.000000  2.300790e+05     966.000000
25%      326.000000    953.500000  3.175006e+06   18960.000000
50%      780.000000   2476.000000  7.356481e+06   44026.000000
75%     1276.000000   4490.000000  1.054673e+07   70130.000000
max    14674.000000  37367.000000  1.132287e+08  718621.000000
publishedAt      0
dislikeCount    12
url             12
id               0
commentCount    12
title            0
viewCount       12
likeCount       12
dtype: int64

In [5]:
print(df.columns)

Index(['dislikeCount', 'commentCount', 'viewCount', 'likeCount',
       'publishedAt_2012-10-04T17:40:09.000Z',
       'publishedAt_2012-10-05T14:16:26.000Z',
       'publishedAt_2012-10-11T03:00:42.000Z',
       'publishedAt_2012-10-11T03:03:47.000Z',
       'publishedAt_2012-10-18T03:54:46.000Z',
       'publishedAt_2012-10-18T14:54:31.000Z',
       ...
       'title_The Van and Mike Show - Substitute Teacher Pt. 2 - Uncensored',
       'title_The Van and Mike Show - The Batmans - Uncensored',
       'title_The Van and Mike Show - Wendell's Defective Superman Bed - Uncensored',
       'title_Vandaveon and Mike Fix Key & Peele - Episode 1 - Uncensored',
       'title_Vandaveon and Mike Fix Key & Peele - Episode 2 - Uncensored',
       'title_Vandaveon and Mike Fix Key & Peele - Episode 4 - Uncensored',
       'title_Vandaveon and Mike Fix Key & Peele - Episode 5 - Uncensored',
       'title_Vandaveon and Mike Fix Key & Peele - Episode 6 - Uncensored',
       'title_Vandaveon and Mike Fix Key & Peele - Episode 7 - Uncensored',
       'title_Vandaveon and Mike Fix Key & Peele - Episode 8 - Uncensored'],
      dtype='str', length=662)

In [10]:
print(df.columns)

target = "your_actual_column_here"  # replace this

if target in df.columns:
    X = df.drop(target, axis=1)
    y = df[target]
else:
    print(f"Column '{target}' not found!")

Index(['publishedAt', 'dislikeCount', 'url', 'id', 'commentCount', 'title',
       'viewCount', 'likeCount'],
      dtype='str')
Column 'your_actual_column_here' not found!

In [17]:
print(df.head())
print(df.columns)

                publishedAt  dislikeCount  ...  viewCount likeCount
0  2016-04-21T21:59:27.000Z         118.0  ...   973798.0    4626.0
1  2015-09-08T15:58:52.000Z        1522.0  ...  5391383.0   36486.0
2  2015-09-08T15:18:07.000Z         574.0  ...  2298981.0   19948.0
3  2015-09-01T19:45:01.000Z         160.0  ...  1070520.0    5861.0
4  2015-08-17T20:09:15.000Z         888.0  ...  8185818.0   79948.0

[5 rows x 8 columns]
Index(['publishedAt', 'dislikeCount', 'url', 'id', 'commentCount', 'title',
       'viewCount', 'likeCount'],
      dtype='str')

In [19]:
print('X_test' in globals())

False

In [27]:
print(df.columns)

Index(['publishedAt', 'dislikeCount', 'url', 'id', 'commentCount', 'title',
       'viewCount', 'likeCount'],
      dtype='str')

In [28]:
print(df.head())

                publishedAt  dislikeCount  ...  viewCount likeCount
0  2016-04-21T21:59:27.000Z         118.0  ...   973798.0    4626.0
1  2015-09-08T15:58:52.000Z        1522.0  ...  5391383.0   36486.0
2  2015-09-08T15:18:07.000Z         574.0  ...  2298981.0   19948.0
3  2015-09-01T19:45:01.000Z         160.0  ...  1070520.0    5861.0
4  2015-08-17T20:09:15.000Z         888.0  ...  8185818.0   79948.0

[5 rows x 8 columns]

In [34]:
df.head()

                publishedAt  dislikeCount  ...  viewCount likeCount
0  2016-04-21T21:59:27.000Z         118.0  ...   973798.0    4626.0
1  2015-09-08T15:58:52.000Z        1522.0  ...  5391383.0   36486.0
2  2015-09-08T15:18:07.000Z         574.0  ...  2298981.0   19948.0
3  2015-09-01T19:45:01.000Z         160.0  ...  1070520.0    5861.0
4  2015-08-17T20:09:15.000Z         888.0  ...  8185818.0   79948.0

[5 rows x 8 columns]

In [37]:
print("X_train" in globals(), "y_train" in globals())

False False

In [41]:
print(df.columns)

Index(['publishedAt', 'dislikeCount', 'url', 'id', 'commentCount', 'title',
       'viewCount', 'likeCount'],
      dtype='str')

In [42]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['publishedAt', 'dislikeCount', 'url', 'id', 'commentCount', 'title',
       'viewCount', 'likeCount'],
      dtype='str')

In [43]:
df.head()

                publishedAt  dislikeCount  ...  viewCount likeCount
0  2016-04-21T21:59:27.000Z         118.0  ...   973798.0    4626.0
1  2015-09-08T15:58:52.000Z        1522.0  ...  5391383.0   36486.0
2  2015-09-08T15:18:07.000Z         574.0  ...  2298981.0   19948.0
3  2015-09-01T19:45:01.000Z         160.0  ...  1070520.0    5861.0
4  2015-08-17T20:09:15.000Z         888.0  ...  8185818.0   79948.0

[5 rows x 8 columns]

In [50]:
df.head()      # first 5 rows
df.tail()      # last 5 rows

                  publishedAt  dislikeCount  ... viewCount likeCount
194  2011-11-15T22:30:33.000Z          35.0  ...  230079.0    1028.0
195  2011-11-15T22:30:33.000Z           NaN  ...       NaN       NaN
196  2011-11-15T22:30:33.000Z           NaN  ...       NaN       NaN
197  2011-11-15T22:30:33.000Z           NaN  ...       NaN       NaN
198  2011-11-15T22:30:33.000Z           NaN  ...       NaN       NaN

[5 rows x 8 columns]