In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file
df = pd.read_csv("Match Dates.csv")

# Preview data
df.head()

         Date  Number of Injuries  Week     Season
0   5/09/2012                   1     1  2012/2013
1  17/09/2012                   1     2  2012/2013
2  27/09/2012                   1     4  2012/2013
3  22/10/2012                   1     7  2012/2013
4  29/10/2012                   1     8  2012/2013

In [4]:
print(df.columns)

Index(['Date', 'Number of Injuries', 'Week', 'Season'], dtype='str')

In [5]:
df.columns = df.columns.str.strip()

text_column = "Match_Info"

if text_column in df.columns:
    df = df.dropna(subset=[text_column])
    df[text_column] = df[text_column].str.lower()
else:
    print(f"Column '{text_column}' not found. Available columns: {df.columns.tolist()}")

Column 'Match_Info' not found. Available columns: ['Date', 'Number of Injuries', 'Week', 'Season']

In [7]:
print(df.columns)

Index(['Date', 'Number of Injuries', 'Week', 'Season'], dtype='str')

In [8]:
def preprocess(text):
    tokens = word_tokenize(str(text).lower())  # lowercase + handle NaN
    tokens = [word for word in tokens if word.isalnum()]
    tokens = [word for word in tokens if word not in stop_words]
    return " ".join(tokens)

In [9]:
if text_column not in df.columns:
    print(f"Column '{text_column}' not found. Available columns:", df.columns)

Column 'Match_Info' not found. Available columns: Index(['Date', 'Number of Injuries', 'Week', 'Season'], dtype='str')

In [13]:
print(df.columns)

Index(['Date', 'Number of Injuries', 'Week', 'Season'], dtype='str')

In [15]:
from sklearn.cluster import KMeans

# Select features
X = df.select_dtypes(include=["number"])

# Choose number of clusters
k = 5

# Fit KMeans
kmeans = KMeans(n_clusters=k, random_state=42)
df["cluster"] = kmeans.fit_predict(X)

df.head()

         Date  Number of Injuries  Week     Season  cluster
0   5/09/2012                   1     1  2012/2013        3
1  17/09/2012                   1     2  2012/2013        3
2  27/09/2012                   1     4  2012/2013        3
3  22/10/2012                   1     7  2012/2013        1
4  29/10/2012                   1     8  2012/2013        1

In [16]:
# Count of items per cluster
df["cluster"].value_counts()

cluster
3    38
1    36
4    34
0    30
2    20
Name: count, dtype: int64

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans

documents = [
    "I love machine learning",
    "KMeans clustering is useful",
    "Text data needs vectorization",
    "I enjoy learning Python"
]

k = 2  # number of clusters

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

kmeans = KMeans(n_clusters=k)
kmeans.fit(X)

terms = vectorizer.get_feature_names_out()
centroids = kmeans.cluster_centers_.argsort()[:, ::-1]

for i in range(k):
    print(f"\nCluster {i}:")
    for j in centroids[i, :10]:
        print(terms[j], end=" ")

Cluster 0:
learning useful python machine love kmeans is enjoy clustering vectorization
Cluster 1:
vectorization text needs data useful python machine love learning kmeans